// <auto-generated />
using BvgAuthApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BvgAuthApi.Migrations
{
    [DbContext(typeof(BvgDbContext))]
    [Migration("20250903194500_AddVoteConstraints")]
    partial class AddVoteConstraints
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
